// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: poetry.proto

package com.cjl.poetryfan.proto;

public final class poetryProto {
  private poetryProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface poetryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:poetry.poetry)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string author = 1;</code>
     */
    boolean hasAuthor();
    /**
     * <code>optional string author = 1;</code>
     */
    java.lang.String getAuthor();
    /**
     * <code>optional string author = 1;</code>
     */
    com.google.protobuf.ByteString
        getAuthorBytes();

    /**
     * <code>optional string birth = 2;</code>
     */
    boolean hasBirth();
    /**
     * <code>optional string birth = 2;</code>
     */
    java.lang.String getBirth();
    /**
     * <code>optional string birth = 2;</code>
     */
    com.google.protobuf.ByteString
        getBirthBytes();

    /**
     * <code>optional string title = 3;</code>
     */
    boolean hasTitle();
    /**
     * <code>optional string title = 3;</code>
     */
    java.lang.String getTitle();
    /**
     * <code>optional string title = 3;</code>
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <code>optional string content = 4;</code>
     */
    boolean hasContent();
    /**
     * <code>optional string content = 4;</code>
     */
    java.lang.String getContent();
    /**
     * <code>optional string content = 4;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <code>optional string head_img = 5;</code>
     */
    boolean hasHeadImg();
    /**
     * <code>optional string head_img = 5;</code>
     */
    java.lang.String getHeadImg();
    /**
     * <code>optional string head_img = 5;</code>
     */
    com.google.protobuf.ByteString
        getHeadImgBytes();
  }
  /**
   * Protobuf type {@code poetry.poetry}
   */
  public static final class poetry extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:poetry.poetry)
      poetryOrBuilder {
    // Use poetry.newBuilder() to construct.
    private poetry(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private poetry(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final poetry defaultInstance;
    public static poetry getDefaultInstance() {
      return defaultInstance;
    }

    public poetry getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private poetry(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              author_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              birth_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              title_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              content_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              headImg_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cjl.poetryfan.proto.poetryProto.internal_static_poetry_poetry_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cjl.poetryfan.proto.poetryProto.internal_static_poetry_poetry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cjl.poetryfan.proto.poetryProto.poetry.class, com.cjl.poetryfan.proto.poetryProto.poetry.Builder.class);
    }

    public static com.google.protobuf.Parser<poetry> PARSER =
        new com.google.protobuf.AbstractParser<poetry>() {
      public poetry parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new poetry(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<poetry> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int AUTHOR_FIELD_NUMBER = 1;
    private java.lang.Object author_;
    /**
     * <code>optional string author = 1;</code>
     */
    public boolean hasAuthor() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string author = 1;</code>
     */
    public java.lang.String getAuthor() {
      java.lang.Object ref = author_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          author_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string author = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAuthorBytes() {
      java.lang.Object ref = author_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        author_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BIRTH_FIELD_NUMBER = 2;
    private java.lang.Object birth_;
    /**
     * <code>optional string birth = 2;</code>
     */
    public boolean hasBirth() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string birth = 2;</code>
     */
    public java.lang.String getBirth() {
      java.lang.Object ref = birth_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          birth_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string birth = 2;</code>
     */
    public com.google.protobuf.ByteString
        getBirthBytes() {
      java.lang.Object ref = birth_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        birth_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TITLE_FIELD_NUMBER = 3;
    private java.lang.Object title_;
    /**
     * <code>optional string title = 3;</code>
     */
    public boolean hasTitle() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string title = 3;</code>
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          title_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string title = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTENT_FIELD_NUMBER = 4;
    private java.lang.Object content_;
    /**
     * <code>optional string content = 4;</code>
     */
    public boolean hasContent() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string content = 4;</code>
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          content_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string content = 4;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HEAD_IMG_FIELD_NUMBER = 5;
    private java.lang.Object headImg_;
    /**
     * <code>optional string head_img = 5;</code>
     */
    public boolean hasHeadImg() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string head_img = 5;</code>
     */
    public java.lang.String getHeadImg() {
      java.lang.Object ref = headImg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          headImg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string head_img = 5;</code>
     */
    public com.google.protobuf.ByteString
        getHeadImgBytes() {
      java.lang.Object ref = headImg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        headImg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      author_ = "";
      birth_ = "";
      title_ = "";
      content_ = "";
      headImg_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getAuthorBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getBirthBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getTitleBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getContentBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getHeadImgBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getAuthorBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getBirthBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getTitleBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getContentBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getHeadImgBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.cjl.poetryfan.proto.poetryProto.poetry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cjl.poetryfan.proto.poetryProto.poetry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cjl.poetryfan.proto.poetryProto.poetry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cjl.poetryfan.proto.poetryProto.poetry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cjl.poetryfan.proto.poetryProto.poetry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cjl.poetryfan.proto.poetryProto.poetry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.cjl.poetryfan.proto.poetryProto.poetry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.cjl.poetryfan.proto.poetryProto.poetry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.cjl.poetryfan.proto.poetryProto.poetry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cjl.poetryfan.proto.poetryProto.poetry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.cjl.poetryfan.proto.poetryProto.poetry prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code poetry.poetry}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:poetry.poetry)
        com.cjl.poetryfan.proto.poetryProto.poetryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cjl.poetryfan.proto.poetryProto.internal_static_poetry_poetry_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cjl.poetryfan.proto.poetryProto.internal_static_poetry_poetry_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cjl.poetryfan.proto.poetryProto.poetry.class, com.cjl.poetryfan.proto.poetryProto.poetry.Builder.class);
      }

      // Construct using com.cjl.poetryfan.proto.poetryProto.poetry.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        author_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        birth_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        title_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        content_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        headImg_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cjl.poetryfan.proto.poetryProto.internal_static_poetry_poetry_descriptor;
      }

      public com.cjl.poetryfan.proto.poetryProto.poetry getDefaultInstanceForType() {
        return com.cjl.poetryfan.proto.poetryProto.poetry.getDefaultInstance();
      }

      public com.cjl.poetryfan.proto.poetryProto.poetry build() {
        com.cjl.poetryfan.proto.poetryProto.poetry result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.cjl.poetryfan.proto.poetryProto.poetry buildPartial() {
        com.cjl.poetryfan.proto.poetryProto.poetry result = new com.cjl.poetryfan.proto.poetryProto.poetry(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.author_ = author_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.birth_ = birth_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.title_ = title_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.content_ = content_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.headImg_ = headImg_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cjl.poetryfan.proto.poetryProto.poetry) {
          return mergeFrom((com.cjl.poetryfan.proto.poetryProto.poetry)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.cjl.poetryfan.proto.poetryProto.poetry other) {
        if (other == com.cjl.poetryfan.proto.poetryProto.poetry.getDefaultInstance()) return this;
        if (other.hasAuthor()) {
          bitField0_ |= 0x00000001;
          author_ = other.author_;
          onChanged();
        }
        if (other.hasBirth()) {
          bitField0_ |= 0x00000002;
          birth_ = other.birth_;
          onChanged();
        }
        if (other.hasTitle()) {
          bitField0_ |= 0x00000004;
          title_ = other.title_;
          onChanged();
        }
        if (other.hasContent()) {
          bitField0_ |= 0x00000008;
          content_ = other.content_;
          onChanged();
        }
        if (other.hasHeadImg()) {
          bitField0_ |= 0x00000010;
          headImg_ = other.headImg_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.cjl.poetryfan.proto.poetryProto.poetry parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.cjl.poetryfan.proto.poetryProto.poetry) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object author_ = "";
      /**
       * <code>optional string author = 1;</code>
       */
      public boolean hasAuthor() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string author = 1;</code>
       */
      public java.lang.String getAuthor() {
        java.lang.Object ref = author_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            author_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string author = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAuthorBytes() {
        java.lang.Object ref = author_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          author_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string author = 1;</code>
       */
      public Builder setAuthor(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        author_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string author = 1;</code>
       */
      public Builder clearAuthor() {
        bitField0_ = (bitField0_ & ~0x00000001);
        author_ = getDefaultInstance().getAuthor();
        onChanged();
        return this;
      }
      /**
       * <code>optional string author = 1;</code>
       */
      public Builder setAuthorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        author_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object birth_ = "";
      /**
       * <code>optional string birth = 2;</code>
       */
      public boolean hasBirth() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string birth = 2;</code>
       */
      public java.lang.String getBirth() {
        java.lang.Object ref = birth_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            birth_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string birth = 2;</code>
       */
      public com.google.protobuf.ByteString
          getBirthBytes() {
        java.lang.Object ref = birth_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          birth_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string birth = 2;</code>
       */
      public Builder setBirth(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        birth_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string birth = 2;</code>
       */
      public Builder clearBirth() {
        bitField0_ = (bitField0_ & ~0x00000002);
        birth_ = getDefaultInstance().getBirth();
        onChanged();
        return this;
      }
      /**
       * <code>optional string birth = 2;</code>
       */
      public Builder setBirthBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        birth_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object title_ = "";
      /**
       * <code>optional string title = 3;</code>
       */
      public boolean hasTitle() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string title = 3;</code>
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            title_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string title = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string title = 3;</code>
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string title = 3;</code>
       */
      public Builder clearTitle() {
        bitField0_ = (bitField0_ & ~0x00000004);
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      /**
       * <code>optional string title = 3;</code>
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        title_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object content_ = "";
      /**
       * <code>optional string content = 4;</code>
       */
      public boolean hasContent() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string content = 4;</code>
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            content_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string content = 4;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string content = 4;</code>
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string content = 4;</code>
       */
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000008);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>optional string content = 4;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        content_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object headImg_ = "";
      /**
       * <code>optional string head_img = 5;</code>
       */
      public boolean hasHeadImg() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string head_img = 5;</code>
       */
      public java.lang.String getHeadImg() {
        java.lang.Object ref = headImg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            headImg_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string head_img = 5;</code>
       */
      public com.google.protobuf.ByteString
          getHeadImgBytes() {
        java.lang.Object ref = headImg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          headImg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string head_img = 5;</code>
       */
      public Builder setHeadImg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        headImg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string head_img = 5;</code>
       */
      public Builder clearHeadImg() {
        bitField0_ = (bitField0_ & ~0x00000010);
        headImg_ = getDefaultInstance().getHeadImg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string head_img = 5;</code>
       */
      public Builder setHeadImgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        headImg_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:poetry.poetry)
    }

    static {
      defaultInstance = new poetry(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:poetry.poetry)
  }

  public interface day_suggestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:poetry.day_suggest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>required string date = 2;</code>
     */
    boolean hasDate();
    /**
     * <code>required string date = 2;</code>
     */
    java.lang.String getDate();
    /**
     * <code>required string date = 2;</code>
     */
    com.google.protobuf.ByteString
        getDateBytes();

    /**
     * <code>required .poetry.poetry poetry = 3;</code>
     */
    boolean hasPoetry();
    /**
     * <code>required .poetry.poetry poetry = 3;</code>
     */
    com.cjl.poetryfan.proto.poetryProto.poetry getPoetry();
    /**
     * <code>required .poetry.poetry poetry = 3;</code>
     */
    com.cjl.poetryfan.proto.poetryProto.poetryOrBuilder getPoetryOrBuilder();
  }
  /**
   * Protobuf type {@code poetry.day_suggest}
   */
  public static final class day_suggest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:poetry.day_suggest)
      day_suggestOrBuilder {
    // Use day_suggest.newBuilder() to construct.
    private day_suggest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private day_suggest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final day_suggest defaultInstance;
    public static day_suggest getDefaultInstance() {
      return defaultInstance;
    }

    public day_suggest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private day_suggest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              date_ = bs;
              break;
            }
            case 26: {
              com.cjl.poetryfan.proto.poetryProto.poetry.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = poetry_.toBuilder();
              }
              poetry_ = input.readMessage(com.cjl.poetryfan.proto.poetryProto.poetry.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(poetry_);
                poetry_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cjl.poetryfan.proto.poetryProto.internal_static_poetry_day_suggest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cjl.poetryfan.proto.poetryProto.internal_static_poetry_day_suggest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cjl.poetryfan.proto.poetryProto.day_suggest.class, com.cjl.poetryfan.proto.poetryProto.day_suggest.Builder.class);
    }

    public static com.google.protobuf.Parser<day_suggest> PARSER =
        new com.google.protobuf.AbstractParser<day_suggest>() {
      public day_suggest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new day_suggest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<day_suggest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int DATE_FIELD_NUMBER = 2;
    private java.lang.Object date_;
    /**
     * <code>required string date = 2;</code>
     */
    public boolean hasDate() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string date = 2;</code>
     */
    public java.lang.String getDate() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          date_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string date = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDateBytes() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        date_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int POETRY_FIELD_NUMBER = 3;
    private com.cjl.poetryfan.proto.poetryProto.poetry poetry_;
    /**
     * <code>required .poetry.poetry poetry = 3;</code>
     */
    public boolean hasPoetry() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required .poetry.poetry poetry = 3;</code>
     */
    public com.cjl.poetryfan.proto.poetryProto.poetry getPoetry() {
      return poetry_;
    }
    /**
     * <code>required .poetry.poetry poetry = 3;</code>
     */
    public com.cjl.poetryfan.proto.poetryProto.poetryOrBuilder getPoetryOrBuilder() {
      return poetry_;
    }

    private void initFields() {
      id_ = 0;
      date_ = "";
      poetry_ = com.cjl.poetryfan.proto.poetryProto.poetry.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDate()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPoetry()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getDateBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, poetry_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getDateBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, poetry_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.cjl.poetryfan.proto.poetryProto.day_suggest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cjl.poetryfan.proto.poetryProto.day_suggest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cjl.poetryfan.proto.poetryProto.day_suggest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cjl.poetryfan.proto.poetryProto.day_suggest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cjl.poetryfan.proto.poetryProto.day_suggest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cjl.poetryfan.proto.poetryProto.day_suggest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.cjl.poetryfan.proto.poetryProto.day_suggest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.cjl.poetryfan.proto.poetryProto.day_suggest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.cjl.poetryfan.proto.poetryProto.day_suggest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cjl.poetryfan.proto.poetryProto.day_suggest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.cjl.poetryfan.proto.poetryProto.day_suggest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code poetry.day_suggest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:poetry.day_suggest)
        com.cjl.poetryfan.proto.poetryProto.day_suggestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cjl.poetryfan.proto.poetryProto.internal_static_poetry_day_suggest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cjl.poetryfan.proto.poetryProto.internal_static_poetry_day_suggest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cjl.poetryfan.proto.poetryProto.day_suggest.class, com.cjl.poetryfan.proto.poetryProto.day_suggest.Builder.class);
      }

      // Construct using com.cjl.poetryfan.proto.poetryProto.day_suggest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPoetryFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        date_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (poetryBuilder_ == null) {
          poetry_ = com.cjl.poetryfan.proto.poetryProto.poetry.getDefaultInstance();
        } else {
          poetryBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cjl.poetryfan.proto.poetryProto.internal_static_poetry_day_suggest_descriptor;
      }

      public com.cjl.poetryfan.proto.poetryProto.day_suggest getDefaultInstanceForType() {
        return com.cjl.poetryfan.proto.poetryProto.day_suggest.getDefaultInstance();
      }

      public com.cjl.poetryfan.proto.poetryProto.day_suggest build() {
        com.cjl.poetryfan.proto.poetryProto.day_suggest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.cjl.poetryfan.proto.poetryProto.day_suggest buildPartial() {
        com.cjl.poetryfan.proto.poetryProto.day_suggest result = new com.cjl.poetryfan.proto.poetryProto.day_suggest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.date_ = date_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (poetryBuilder_ == null) {
          result.poetry_ = poetry_;
        } else {
          result.poetry_ = poetryBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cjl.poetryfan.proto.poetryProto.day_suggest) {
          return mergeFrom((com.cjl.poetryfan.proto.poetryProto.day_suggest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.cjl.poetryfan.proto.poetryProto.day_suggest other) {
        if (other == com.cjl.poetryfan.proto.poetryProto.day_suggest.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasDate()) {
          bitField0_ |= 0x00000002;
          date_ = other.date_;
          onChanged();
        }
        if (other.hasPoetry()) {
          mergePoetry(other.getPoetry());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasDate()) {
          
          return false;
        }
        if (!hasPoetry()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.cjl.poetryfan.proto.poetryProto.day_suggest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.cjl.poetryfan.proto.poetryProto.day_suggest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object date_ = "";
      /**
       * <code>required string date = 2;</code>
       */
      public boolean hasDate() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string date = 2;</code>
       */
      public java.lang.String getDate() {
        java.lang.Object ref = date_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            date_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string date = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDateBytes() {
        java.lang.Object ref = date_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          date_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string date = 2;</code>
       */
      public Builder setDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        date_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string date = 2;</code>
       */
      public Builder clearDate() {
        bitField0_ = (bitField0_ & ~0x00000002);
        date_ = getDefaultInstance().getDate();
        onChanged();
        return this;
      }
      /**
       * <code>required string date = 2;</code>
       */
      public Builder setDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        date_ = value;
        onChanged();
        return this;
      }

      private com.cjl.poetryfan.proto.poetryProto.poetry poetry_ = com.cjl.poetryfan.proto.poetryProto.poetry.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.cjl.poetryfan.proto.poetryProto.poetry, com.cjl.poetryfan.proto.poetryProto.poetry.Builder, com.cjl.poetryfan.proto.poetryProto.poetryOrBuilder> poetryBuilder_;
      /**
       * <code>required .poetry.poetry poetry = 3;</code>
       */
      public boolean hasPoetry() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required .poetry.poetry poetry = 3;</code>
       */
      public com.cjl.poetryfan.proto.poetryProto.poetry getPoetry() {
        if (poetryBuilder_ == null) {
          return poetry_;
        } else {
          return poetryBuilder_.getMessage();
        }
      }
      /**
       * <code>required .poetry.poetry poetry = 3;</code>
       */
      public Builder setPoetry(com.cjl.poetryfan.proto.poetryProto.poetry value) {
        if (poetryBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          poetry_ = value;
          onChanged();
        } else {
          poetryBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .poetry.poetry poetry = 3;</code>
       */
      public Builder setPoetry(
          com.cjl.poetryfan.proto.poetryProto.poetry.Builder builderForValue) {
        if (poetryBuilder_ == null) {
          poetry_ = builderForValue.build();
          onChanged();
        } else {
          poetryBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .poetry.poetry poetry = 3;</code>
       */
      public Builder mergePoetry(com.cjl.poetryfan.proto.poetryProto.poetry value) {
        if (poetryBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              poetry_ != com.cjl.poetryfan.proto.poetryProto.poetry.getDefaultInstance()) {
            poetry_ =
              com.cjl.poetryfan.proto.poetryProto.poetry.newBuilder(poetry_).mergeFrom(value).buildPartial();
          } else {
            poetry_ = value;
          }
          onChanged();
        } else {
          poetryBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .poetry.poetry poetry = 3;</code>
       */
      public Builder clearPoetry() {
        if (poetryBuilder_ == null) {
          poetry_ = com.cjl.poetryfan.proto.poetryProto.poetry.getDefaultInstance();
          onChanged();
        } else {
          poetryBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>required .poetry.poetry poetry = 3;</code>
       */
      public com.cjl.poetryfan.proto.poetryProto.poetry.Builder getPoetryBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getPoetryFieldBuilder().getBuilder();
      }
      /**
       * <code>required .poetry.poetry poetry = 3;</code>
       */
      public com.cjl.poetryfan.proto.poetryProto.poetryOrBuilder getPoetryOrBuilder() {
        if (poetryBuilder_ != null) {
          return poetryBuilder_.getMessageOrBuilder();
        } else {
          return poetry_;
        }
      }
      /**
       * <code>required .poetry.poetry poetry = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.cjl.poetryfan.proto.poetryProto.poetry, com.cjl.poetryfan.proto.poetryProto.poetry.Builder, com.cjl.poetryfan.proto.poetryProto.poetryOrBuilder> 
          getPoetryFieldBuilder() {
        if (poetryBuilder_ == null) {
          poetryBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.cjl.poetryfan.proto.poetryProto.poetry, com.cjl.poetryfan.proto.poetryProto.poetry.Builder, com.cjl.poetryfan.proto.poetryProto.poetryOrBuilder>(
                  getPoetry(),
                  getParentForChildren(),
                  isClean());
          poetry_ = null;
        }
        return poetryBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:poetry.day_suggest)
    }

    static {
      defaultInstance = new day_suggest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:poetry.day_suggest)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_poetry_poetry_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_poetry_poetry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_poetry_day_suggest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_poetry_day_suggest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014poetry.proto\022\006poetry\"Y\n\006poetry\022\016\n\006auth" +
      "or\030\001 \001(\t\022\r\n\005birth\030\002 \001(\t\022\r\n\005title\030\003 \001(\t\022\017" +
      "\n\007content\030\004 \001(\t\022\020\n\010head_img\030\005 \001(\t\"G\n\013day" +
      "_suggest\022\n\n\002id\030\001 \002(\005\022\014\n\004date\030\002 \002(\t\022\036\n\006po" +
      "etry\030\003 \002(\0132\016.poetry.poetryB&\n\027com.cjl.po" +
      "etryfan.protoB\013poetryProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_poetry_poetry_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_poetry_poetry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_poetry_poetry_descriptor,
        new java.lang.String[] { "Author", "Birth", "Title", "Content", "HeadImg", });
    internal_static_poetry_day_suggest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_poetry_day_suggest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_poetry_day_suggest_descriptor,
        new java.lang.String[] { "Id", "Date", "Poetry", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
